[package]
name = "tetris-lib"
version = "0.1.0"
authors = ["Anoop Naravaram <anoop901@gmail.com>"]

[lib]
name = "tetris"
path = "src/lib.rs"

[[bin]]
name = "tetris_cli"
path = "src/main.rs"

[dependencies]
rand = {version = "0.6", features = ["wasm-bindgen"]}
prettytable-rs = "*"
